## 프로미스 체이닝

* 비동기식 처리 모델(Asynchronous processing model 또는 Non-Blocking processing model)

> 병렬적으로 태스크를 수행하는 모델입니다. 즉, 태스크가 종료되지 않은 상태라 하더라도 대기하지 않고 **즉시 다음 태스크를 실행합니다.**  예를 들어 서버에서 데이터를 가져와서 화면에 표시하는 태스크를 수행할 때, 서버에 데이터를 요청한 이후 서버로부터 데이터가 응답될 때까지 대기하지 않고(Non-Blocking) 즉시 다음 태스크를 수행합니다.  자바스크립트의 대부분의 **DOM 이벤트**와 **Timer 함수(setTimeout, setInterval)**, **Ajax 요청**은 비동기식 처리 모델로 동작합니다.

#### 1. 프로미스 체이닝 이유

비동기 함수의 처리 결과를 가지고 다른 비동기 함수를 호출해야 하는 경우, 함수의 호출이 중첩(nesting)이 되어 복잡도가 높아지는 ```콜백 헬```이 발생합니다. 프로미스는 후속 처리 메소드를 체이닝(chainning)하여 여러 개의 프로미스를 연결하여 사용할 수 있다. 이로써 콜백 헬을 해결 할 수 있습니다.

#### 2. 프로미스 체이닝

 여러 개의 프로미스를 연결하여 사용 하는 것을 말합니다. 프로미스의 `then()` 메서드를 호출하여 여러개의 프로미스를 연결 합니다. 

프로미스 체이닝을 사용하게 되면 ```콜백은 주어진 순서대로 하나 하나 실행되게 됩니다.```

```js
new Promise(function(resolve, reject) {

  setTimeout(() => resolve(1), 1000); // (*)

}).then(function(result) { // (**)

  alert(result); // 1
  return result * 2;

}).then(function(result) { // (***)

  alert(result); // 2
  return result * 2;

}).then(function(result) {

  alert(result); // 4
  return result * 2;

});
```

위 예시는 아래와 같은 순서로 실행됩니다.

1. 1초 후 최초 프라미스가 이행됩니다. – `(*)`
2. 이후 첫번째 `.then` 핸들러가 호출됩니다. –`(**)`
3. 2에서 반환한 값은 다음 `.then` 핸들러에 전달됩니다. – `(***)`
4. 이런 과정이 계속 이어집니다.

`result`가 핸들러 체인을 따라 전달되므로, `alert` 창엔 `1`, `2`, `4`가 순서대로 출력됩니다.

프라미스 체이닝이 가능한 이유는 `promise.then`을 호출하면 프라미스가 반환되기 때문입니다. 반환된 프라미스엔 당연히 `.then`을 호출할 수 있습니다.

<img src="https://ko.javascript.info/article/promise-chaining/promise-then-chain.svg" />

* ES2017에는 promise chaining 기술을 사용하는 것보다 더 깔끔한 코드를 작성하는 데 도움이 되는 async/await가 도입되었습니다.

* 에러는 catch를 통해 처리가 가능합니다.

  ```js
  promiseGet(userData){ 
      .then(파싱) 
      .then(인증) 
      .catch(err)
  }
  ```

#### 3. 프로미스 후속처리 메소드

1. ```.then()``` 두 개의 콜백 함수를 인자로 전달 받습니다. 첫 번째 콜백 함수는 성공(fulfilled, resolve 함수가 호출된 상태) 시 호출되고 두 번째 함수는 실패(rejected, reject 함수가 호출된 상태) 시 호출됩니다.

```js
let promise = new Promise(function(resolve, reject) {
    resolve('Resolving a fake Promise.');
});

promise.then(function(value) {
    console.log(value);
})
```

2. ```.catch()```는예외(비동기 처리에서 발생한 에러와 then 메소드에서 발생한 에러)가 발생하면 호출됩니다. catch 메소드는 Promise를 반환합니다.

   ```js
   const promise = new Promise(function(resolve, reject) {
       reject(401);
   });
   
   promise
   .catch(function(error) {
       if (error === 401) {
           console.log('Rethrowing the 401');
           throw error;
       } else {
           //...
       }
   })
   .then(function(value) {
       console.log(value);
   }).catch(function(error) {
       // Rethrow 
       console.log(`handling ${error} here`);
   });
   
   //결과
   Rethrowing the 401
   handling 401 here
   ```

   