개발을 하다보면 자체 에러 클래스가 필요한 경우가 종종 생깁니다.

`Error`를 상속받아 에러 객체를 만드는 것이 더 좋습니다.
* `throw`의 인수에는 제약이 없기 때문에 커스텀 에러 클래스는 반드시 `Error`를 상속할 필요가 없습니다.
* 그러나, `Error`를 상속받아 에러 객체를 만들면 `obj instanceof Error`를 사용해서 에러 객체 식별 가능다는 장점이 존재합니다.

# 에러 확장하기
사용자 데이터가 저장된 JSON을 `JSON.parse`를 사용해 읽고 데이터를 검증하는 함수 `readUser(json)`이 존재한다고 해봅시다.
* 예외 발생 가능 상황
  1. 잘못된 형식의 `json`이 들어오면 `SyntaxError`가 발생
  2. 필수 프로퍼티가 없는 잘못된 데이터가 들어올 경우, 에러를 발생시켜야함

2번 예외 상황을 처리하기 위해 커스텀 에러 객체(`ValidateionError`)를 생성
* 내장 클래스 `Error` 상속

먼저, 슈도 코드로 `Error`클래스의 모습을 살펴봅시다.
```javascript
// 자바스크립트 자체 내장 에러 클래스 Error의 '슈도 코드'
class Error {
  constructor(message) {
    this.message = message;
    this.name = "Error"; // (name은 내장 에러 클래스마다 다릅니다.)
    this.stack = <call stack>;  // stack은 표준은 아니지만, 대다수 환경이 지원합니다.
  }
}
```

`ValidateionError`에서 `Error`를 상속받아보겠습니다.
```javascript
class ValidationError extends Error {
  constructor(message) {
    super(message); // (1) 
    this.name = "ValidationError"; // (2)
  }
}

function test() {
  throw new ValidationError("에러 발생!");
}

try {
  test();
} catch(err) {
  alert(err.message); // 에러 발생!
  alert(err.name); // ValidationError
  alert(err.stack); // 각 행 번호가 있는 중첩된 호출들의 목록
}
```

1. 부모 생성자 호출 : JS에서는 자식 생성자 안에서 `super`를 반드시 호출해야합니다.
2. 부모 생성자에서 `name`프로퍼티를 설정하기 때문에 원하는 값으로 재설정합니다.

### `readUser(json)` 안에서 `ValidationError`를 사용하기
```javascript
class ValidationError extends Error {
  constructor(message) {
    super(message);
    this.name = "ValidationError";
  }
}

// 사용법
function readUser(json) {
  let user = JSON.parse(json);

  if (!user.age) {
    throw new ValidationError("No field: age");
  }
  if (!user.name) {
    throw new ValidationError("No field: name");
  }

  return user;
}

// try..catch와 readUser를 함께 사용한 예시

try {
  let user = readUser('{ "age": 25 }');
} catch (err) {
  if (err instanceof ValidationError) {
    alert("Invalid data: " + err.message); // Invalid data: No field: name
  } else if (err instanceof SyntaxError) { // (*) instanceof로 에러 유형을 확인
    alert("JSON Syntax Error: " + err.message);
  } else {
    throw err; // 알려지지 않은 에러는 재던지기 합니다. (**)
  }
}
```

에러 유형 확인은 `err.name`을 사용해도 가능하지만 `instanceof`를 사용하는 것이 좋습니다.
* 새로운 상속 클래스에서도 동작하기 때문

# 더 깊게 상속하기
`ValidationError` 보다 더 구체적인 클래스 `PropertyRequiredError`를 생성해봅시다.
* `PropertyRequiredError`는 필수 프로퍼티가 없는 경우에 대응
* `PropertyRequiredError`엔 누락된 프로퍼티에 대한 추가 정보가 담겨야 합니다.

```javascript
class ValidationError extends Error {
  constructor(message) {
    super(message);
    this.name = "ValidationError";
  }
}

class PropertyRequiredError extends ValidationError {
  constructor(property) {
    super("No property: " + property);
    this.name = "PropertyRequiredError";
    this.property = property;
  }
}

// 사용법
function readUser(json) {
  let user = JSON.parse(json);

  if (!user.age) {
    throw new PropertyRequiredError("age");
  }
  if (!user.name) {
    throw new PropertyRequiredError("name");
  }

  return user;
}

// try..catch와 readUser를 함께 사용하면 다음과 같습니다.

try {
  let user = readUser('{ "age": 25 }');
} catch (err) {
  if (err instanceof ValidationError) {
    alert("Invalid data: " + err.message); // Invalid data: No property: name
    alert(err.name); // PropertyRequiredError
    alert(err.property); // name
  } else if (err instanceof SyntaxError) {
    alert("JSON Syntax Error: " + err.message);
  } else {
    throw err; // 알려지지 않은 에러는 재던지기 합니다.
  }
}
```
### 기본 에러 생성자 만들기

`PropertyRequiredError` 생성자 안에서 `this.name`을 수동으로 할당해 주었다는 것입니다. 그런데 이렇게 매번 커스텀 에러 클래스의 생성자 안에서 `this.name`를 할당해 주는 것은 귀찮은 작업입니다. 이런 번거로운 작업은 **‘기본 에러’ 클래스를 만들고 커스텀 에러들이 이 클래스를 상속받**게 하면 피할 수 있습니다. **기본 에러의 생성자에 `this.name = this.constructor.name`를 추가**하면 되죠.

기본 에러 클래스를 `MyError`라고 부르겠습니다.

`MyError`를 사용하면 다음과 같이 커스텀 에러 클래스를 간결하게 할 수 있습니다.
```javascript
class MyError extends Error {
  constructor(message) {
    super(message);
    this.name = this.constructor.name;
  }
}

class ValidationError extends MyError { }

class PropertyRequiredError extends ValidationError {
  constructor(property) {
    super("No property: " + property);
    this.property = property;
  }
}

// 제대로 된 이름이 출력됩니다.
alert( new PropertyRequiredError("field").name ); // PropertyRequiredError
```

# 예외 감싸기
사용자 데이터를 읽는 과정에서 다른 오류가 발생할 수 있습니다. 지금 당장은 `SyntaxError`와 `ValidationError`를 사용해 에러를 처리하고 있는데, 앞으로 `readUser`가 더 커지면 다른 커스텀 에러 클래스를 만들어야 할 겁니다.

`readUser`를 호출하는 곳에선 새롭게 만들어질 커스텀 에러들을 처리할 수 있어야 합니다. 그런데 지금은 종류를 알 수 없는 에러는 다시 던지기를 해 처리하고 있는 실정입니다.

현재 에러 처리 스키마는 다음과 같습니다.

```javascript
try {
  ...
  readUser()  // 잠재적 에러 발생처
  ...
} catch (err) {
  if (err instanceof ValidationError) {
    // validation 에러 처리
  } else if (err instanceof SyntaxError) {
    // 문법 에러 처리
  } else {
    throw err; // 알 수 없는 에러는 다시 던지기 함
  }
}
```

예외 감싸기(wrapping exception)
* 배경
  * 미래에 에러 종류가 추가될 때마다 에러 처리 분기문을 매번 추가하는 것은 번거롭다.
    * 실제 우리가 필요로 하는 정보는 ‘데이터를 읽을 때’ 에러가 발생했는지에 대한 여부입니다. 왜 에러가 발생했는지와 자세한 설명은 대부분의 경우 필요하지 않습니다. 필요할 때 에러 세부사항에 대한 정보를 얻을 수 있는 방법이 있다면 더 좋겠지만 말이죠.
* 정의
  * 예외 감싸기를 적용한 함수에선 모든 에러를 종류별로 처리하지 않습니다. 대신 모든 에러를 포함할 수 있는 추상 에러를 하나 만들고, 에러가 발생하면 이 추상 에러를 던지도록 합니다. 추상 에러를 던질 때 실제 발생한 에러를 추상 에러의 프로퍼티(err.cause)로 넘기면 구체적인 에러 정보를 함께 넘겨줄 수 있는데, 반드시 이 프로퍼티가 있어야 하는 것은 아닙니다.

* 순서
  1. '데이터 읽기’와 같은 포괄적인 에러를 대변하는 새로운 클래스 `ReadError`를 만듭니다.
  2. 함수 `readUser` 발생한 `ValidationError`, `SyntaxError` 등의 에러는 `readUser` 내부에서 잡고 이때 `ReadError`를 생성합니다.
  3. `ReadError` 객체의 `cause` 프로퍼티엔 실제 에러에 대한 참조가 저장됩니다.

이렇게 예외 감싸기 기술을 써 스키마를 변경하면 `readUser`를 호출하는 코드에선 `ReadError`만 확인하면 됩니다. 데이터를 읽을 때 발생하는 에러 종류 전체를 확인하지 않아도 되죠. 추가 정보가 필요한 경우엔 `cause` 프로퍼티를 확인하면 됩니다.

이제 실제로 `ReadError`를 정의하고 이를 사용해보도록 합시다. `ReadError`는 `readUser`와 `try..catch` 안에서 다음과 같은 형태로 사용할 수 있습니다.

```javascript
class ReadError extends Error {
  constructor(message, cause) {
    super(message);
    this.cause = cause;
    this.name = 'ReadError';
  }
}

class ValidationError extends Error { /*...*/ }
class PropertyRequiredError extends ValidationError { /* ... */ }

function validateUser(user) {
  if (!user.age) {
    throw new PropertyRequiredError("age");
  }

  if (!user.name) {
    throw new PropertyRequiredError("name");
  }
}

function readUser(json) {
  let user;

  try {
    user = JSON.parse(json);
  } catch (err) {
    if (err instanceof SyntaxError) {
      throw new ReadError("Syntax Error", err);
    } else {
      throw err;
    }
  }

  try {
    validateUser(user);
  } catch (err) {
    if (err instanceof ValidationError) {
      throw new ReadError("Validation Error", err);
    } else {
      throw err;
    }
  }

}

try {
  readUser('{잘못된 형식의 json}');
} catch (e) {
  if (e instanceof ReadError) {
    alert(e);
    // Original error: SyntaxError: Unexpected token b in JSON at position 1
    alert("Original error: " + e.cause);
  } else {
    throw e;
  }
}
```
예외 감싸기 사용시** 예외가 발생할 수 있는 함수(`readUser`)를 호출하는 바깥 코드에서는 예외 처리 분기문을 여러개 만들 필요없이 `instanceof ReadError` 하나만 확인하면 됩니다.**
